// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sojwucfbcehytucwfggj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvand1Y2ZiY2VoeXR1Y3dmZ2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMzc1NDMsImV4cCI6MjA3MjcxMzU0M30._vEk4imkaiPD8pjQew5gl4XR8tIc6_S9vnhVqIwZH1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});